### ISSUE TITLE
chef-client (version 13) run fails due to deprecation

### ISSUE THREAD

**Issue by y0y0z** [chef-cookbooks/chef_handler#56] opened 2017-06-01 20:22 UTC
### Cookbook version
2.1.1

### Chef-client version
12.20.3

### Platform Details
ubuntu 16.04.2 lts

### Scenario:
incompatibility with chef 13 regardless of [this commit](https://github.com/chef-cookbooks/chef_handler/commit/d1d403b1d6b603c6c95b10033446e4034a12e9ac)

### Steps to Reproduce:
[prepration for chef 13](https://blog.chef.io/2017/01/30/preparing-for-chef-13/)

### Actual Result:
```bash
Chef::Exceptions::DeprecatedFeatureError
----------------------------------------
"Property `supports` of resource `chef_handler` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. (CHEF-11)/home/ubuntu/kitchen/cache/cookbooks/chef_handler/resources/default.rb:31:in `class_from_file'.\nPlease see https://docs.chef.io/deprecations_property_name_collision.html for further details and information on how to correct this problem. at /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/formatters/doc.rb:419:in `deprecation'"
```

**Comment by coderanger** [comment] 2017-06-01 20:27
The warning is red herring, we apologize for the confusion.

**Comment by y0y0z** [comment] 2017-06-01 21:55
@coderanger: with no intention of being rude, can you **please apply your magic once more** and make it disappear? :)

**Comment by coderanger** [comment] 2017-06-01 21:57
Yeah it's planned just no one has gotten to it. We need to make the property definition be version-based.

**Comment by y0y0z** [comment] 2017-06-01 22:11
@coderanger i guess you meant it should follow the [custom resource](https://docs.chef.io/custom_resources.html). i'll check it out and hope i could contribute :)

**Comment by coderanger** [comment] 2017-06-01 22:14
No, the issue is in how we changed the `supports` property in Chef 13 leading to a catch-22 that requires some fancy code to resolve :)

**Comment by iennae** [comment] 2017-06-13 22:13
Despite the warning, this is ok and a false warning as @coderanger mentioned. There isn't a way to ignore this error if you are configuring your run to fail on errors as well at this point. I'm going to go ahead and close this as there isn't anything that can be done right now to change this behavior.

**Closed by iennae** 2017-06-13 22:13 UTC
Labels: Status: Blocked

**Comment by iennae** [comment] 2017-06-21 01:28
With the latest release this should get fixed as "supports" has been renamed to "type".
